BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "Admin" (
	"AID"	INTEGER,
	PRIMARY KEY("AID"),
	FOREIGN KEY("AID") REFERENCES "User"("UID")
);
CREATE TABLE IF NOT EXISTS "Cashier" (
	"CAID"	INTEGER,
	PRIMARY KEY("CAID"),
	FOREIGN KEY("CAID") REFERENCES "User"("UID")
);
CREATE TABLE IF NOT EXISTS "Customer" (
	"CID"	INTEGER,
	PRIMARY KEY("CID"),
	FOREIGN KEY("CID") REFERENCES "Person"("ID")
);
CREATE TABLE IF NOT EXISTS "OrderItem" (
	"PID"	INTEGER,
	"OID"	INTEGER,
	"Desired_Quantity"	INTEGER NOT NULL,
	"Total_Price"	REAL,
	PRIMARY KEY("PID","OID"),
	FOREIGN KEY("OID") REFERENCES "Orders"("ID"),
	FOREIGN KEY("PID") REFERENCES "Product"("ID")
);
CREATE TABLE IF NOT EXISTS "Orders" (
	"ID"	INTEGER,
	"Date"	TEXT NOT NULL,
	"Discount"	REAL,
	"Payment_Method"	TEXT CHECK("Payment_Method" IN ('Cash', 'Credit')),
	"Calculated_Price"	REAL,
	"Total_Price"	REAL,
	"CID"	INTEGER,
	"CAID"	INTEGER,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("CAID") REFERENCES "Cashier"("CAID"),
	FOREIGN KEY("CID") REFERENCES "Customer"("CID")
);
CREATE TABLE IF NOT EXISTS "Person" (
	"ID"	INTEGER,
	"Name"	TEXT NOT NULL,
	"Contact_Info"	TEXT,
	"Type"	TEXT NOT NULL,
	PRIMARY KEY("ID" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "Product" (
	"ID"	INTEGER,
	"Name"	TEXT NOT NULL,
	"Price"	REAL NOT NULL,
	"Quantity"	INTEGER NOT NULL,
	"Status"	TEXT,
	"SID"	INTEGER,
	"Colour"	TEXT,
	PRIMARY KEY("ID" AUTOINCREMENT),
	FOREIGN KEY("SID") REFERENCES "Supplier"("SID")
);
CREATE TABLE IF NOT EXISTS "Supplier" (
	"SID"	INTEGER,
	PRIMARY KEY("SID"),
	FOREIGN KEY("SID") REFERENCES "Person"("ID")
);
CREATE TABLE IF NOT EXISTS "User" (
	"UID"	INTEGER,
	"Email"	TEXT NOT NULL,
	"Password"	TEXT NOT NULL,
	"Type"	TEXT NOT NULL,
	"Salary"	REAL,
	PRIMARY KEY("UID"),
	FOREIGN KEY("UID") REFERENCES "Person"("ID")
);
CREATE TRIGGER auto_insert_from_person
AFTER INSERT ON Person
BEGIN
    -- Customer
    INSERT INTO Customer (CID)
    SELECT NEW.ID
    WHERE NEW.Type = 'CUSTOMER';

    -- Supplier
    INSERT INTO Supplier (SID)
    SELECT NEW.ID
    WHERE NEW.Type = 'SUPPLIER';

    -- User
    INSERT INTO User (UID, Email, Password, Type, Salary)
    SELECT NEW.ID, NEW.Contact_Info, NEW.Name, NEW.Type, NULL
    WHERE NEW.Type = 'USER';
END;
CREATE TRIGGER auto_user_type_update
AFTER UPDATE OF Type ON User
BEGIN
    INSERT INTO Admin (AID)
    SELECT NEW.UID
    WHERE NEW.Type = 'ADMIN';

    INSERT INTO Cashier (CAID)
    SELECT NEW.UID
    WHERE NEW.Type = 'CASHIER';
END;
COMMIT;
